### PR TITLE
Native improvements to Code

### PR DESCRIPTION
**Pull request by MisterBianco**
Using posix library for native functions for accessing values: 

:heavy_check_mark:  Host 
:heavy_check_mark:  User 

as well as a new proc for accessing prompt symbol. :penguin:

### CODE REVIEW

**Comment by icyphox** [comment]
Hi thanks for this PR! I feel it would be great if there's an option for the user to customize the prompt symbol themselves. If you don't mind adding that… I'll keep this PR open.

**Comment by MisterBianco** [comment]
Sorry, for the accidental close. hope this fixes everything.

**Comment by icyphox** [comment]
This is perfect! Love it :)  
Thanks a bunch.

**Comment by MisterBianco** [comment]
It might be worth your or my time to look at libgit2 to make the git queries more performant. -- however libgit is a nightmare and the author of the nim bindings has 0 documentation.

**Comment by icyphox** [comment]
I did consider it, I even attempted writing a Nim wrapper for it. I soon gave up for that very reason -- it's a nightmare. 

Also yes, I've seen the existing Nim wrapper too; no docs whatsoever :(

**Comment by MisterBianco** [comment]
Also I am starting to work on a window manager in nim. I saw your linux rice on reddit and was wondering if you wanted to collab? I will PM you tomorrow.

**Comment by icyphox** [comment]
Oh nice! I was considering attempting something like that myself. Hit me up, I'll be down to collab. Where do you want to discuss this? Twitter?

**Comment by MisterBianco** [comment]
just emailed you

**Pull request merged**
