### PR TITLE
build doc

### PR DESCRIPTION
**Pull request by xyb**
Automate build documentation. The result is: https://xyb.github.io/nicy/

### CODE REVIEW

**Comment by icyphox** [comment]
This is neat! Thanks.

**Comment by xyb** [comment]
@icyphox I have noticed that http://icyphox.github.io/nicy/ is still 404. I think you may want to enable the Github Pages by adding a theme on the repo's setup page. See also: https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-with-the-theme-chooser#adding-a-theme-with-the-theme-chooser

**Comment by icyphox** [comment]
Ah yes completely forgot.  Doesn't seem to work despite having enabled it though… hm.

**Comment by icyphox** [comment]
@xyb I don't think the symlink to index.html works. Perhaps we should `cp nicy.html index.html`?

**Comment by icyphox** [comment]
https://icyphox.github.io/nicy/nicy.html -- this works.

**Comment by xyb** [comment]
> @xyb I don't think the symlink to index.html works. Perhaps we should `cp nicy.html index.html`?

http://icyphox.github.io/nicy/ works now :)

**Comment by xyb** [comment]
@icyphox  `readme.md` is too long. I suggest moving the API document to `functions.nim`.

**Comment by icyphox** [comment]
Does it? Still seems to 404 for me lol.

**Comment by icyphox** [comment]
@xyb yeah you're right. It should be docstrings in the code. I'll get around to that when I have the time.

**Comment by xyb** [comment]
> Does it? Still seems to 404 for me lol.

Ohh, maybe your browser cached the 404 response when you first look at it. Have you tried to force reload the web page?

**Comment by icyphox** [comment]
Yep, tried it in a private tab, and on another machine haha. Seems to be broken.

**Comment by xyb** [comment]
It's wired, I can access it correctly, both http://icyphox.github.io/nicy/ and https://xyb.github.io/nicy/

**Comment by icyphox** [comment]
Looks like https://icyphox.github.io/nicy/index.html works but not https://icyphox.github.io/nicy/

**Comment by xyb** [comment]
I can't believe this :-P Hmm, I had used the symlink index.html file in few projects. Can you see these https://xyb.github.io/leveldb.nim/ and https://xyb.github.io/nimrod-bloom/ ?

**Comment by icyphox** [comment]
Those work, yes. Very weird.

**Comment by icyphox** [comment]
@xyb hah! It works now. :D 

Anyway, thank you for your contributions -- have a great day!

**Pull request merged**
